// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    $("form").on("submit", function() {
      return false;
    });
    return $(".submit").on("click", function(e) {
      e.preventDefault();
      return $.ajax({
        type: 'POST',
        url: 'php/form_handler.php',
        success: function(result) {
          return $("#text").html(result);
        },
        error: function(XHR) {
          return $("body").append("Sorry, there was an error getting the page.  Please try again later");
        },
        data: $('form').serialize() + "&submit=" + $(this).attr("value")
      });
    });
  });

}).call(this);
