// Generated by CoffeeScript 1.8.0
(function() {
  var msg;

  $(document).ready(function() {
    $("form").on("submit", function() {
      return false;
    });
    $(".submit").on("click", function(e) {
      e.preventDefault();
      return $.ajax({
        type: 'POST',
        url: 'php/save.php',
        success: function(result) {
          return msg("Page Saved");
        },
        error: function(XHR) {
          return msg("Error Saving Page");
        },
        data: $('form').serialize()
      });
    });
    return $("#pageSelect").on("change", function() {
      return $.ajax({
        type: 'POST',
        url: 'php/load.php',
        success: function(result) {
          msg("Loaded Page");
          return $("#text").html(result);
        },
        error: function(XHR) {
          return msg("Error Loading Page");
        },
        data: $('form').serialize()
      });
    });
  });

  msg = function(msg) {
    return $("#messageArea").html(msg);
  };

}).call(this);
